#exec i3 -V >> ~/.i3/i3log 2>&1
exec i3

if hash unclutter 2> /dev/null; then                                                 │~                                                                                   
    unclutter -idle 1 & # Autohide mouse cursor                                      │~                                                                                   
fi
