#!/usr/bin/env sh
# Aliases with + zsh specific aliases

test ~/.aliases.sh && source ~/.aliases.sh


alias http='noglob http'
alias git='noglob git'
alias find='noglob find'
alias pip='noglob pip'

alias -g c="xclip -selection clipboard"

