#!/bin/zsh

export EDITOR=/usr/bin/vim
# teamocil: tmux session manager
export TEAMOCIL_PATH=$HOME/.tmux/teamocil/
compctl -g '~/.tmux/teamocil/*(:t:r)' teamocil

# virtualenvwrapper settings
export VIRTUALENVWRAPPER_LOG_DIR="$WORKON_HOME"
export VIRTUALENVWRAPPER_HOOK_DIR="$WORKON_HOME"
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv

if [ -d $HOME/.bin ]; then
    path+=($HOME/.bin)
fi

if [ -d $HOME/.cabal/bin ]; then
    path+=($HOME/.cabal/bin)
fi

if [ -d $HOME/.gem/ruby/2.1.0/bin/ ]; then
    path+=($HOME/.gem/ruby/2.1.0/bin/)
fi

# Set PATH/path to be unique
typeset -U path

export PATH

fpath=(~/.dotfiles/zsh/additional-zsh-completions/src $fpath)

# Colorful man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export TODOTXT_CFG_FILE="$HOME/todo.cfg"
export LESS=-RFX

export PURE_GIT_PULL=0 # Dont check whenever git remote updated

# https://github.com/jahendrie/cheat
export DEFAULT_CHEAT_DIR=$HOME/files/repos/cheats


# Golang env variables
export GOROOT=$HOME/.go/
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin


eval "$($HOME/files/repos/sub/bin/sub init -)"
export TERM=xterm-256color
