# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# ssh-agent forwarding
zstyle :omz:plugins:ssh-agent agent-forwarding on

# screen auto-start
# zstyle :omz:plugins:screen auto-start on

# tmux auto-start
zstyle :omz:plugins:tmux auto-start on

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
    cp
    docker
    git
    git-flow
    history-substring-search
    npm
    pip
    redis-cli
    ssh-agent
    tmux
    extract
    tux
    virtualenvwrapper
)

source $ZSH/oh-my-zsh.sh

setopt histignorespace

# Disable auto correct
unsetopt correct_all

test -f ~/.zsh_aliases && source ~/.zsh_aliases
test -f ~/.local.sh && source ~/.local.sh

#z - autojump alternative
test -f ~/.scripts/z.sh && source ~/.scripts/z.sh

# COMPLETION SETTINGS
# add custom completion scripts
fpath=(~/.dotfiles/zsh/completions $fpath) 

# compsys initialization
autoload -U compinit
compinit

type hub > /dev/null 2>&1 && {
    eval "$(hub alias -s)"
}

source ~/.zshenv

umask 077 # Anybody can't rwx my created files
conky -c ~/.dotfiles/dots/conkyrc > /dev/null 2>&1
